# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Cozy Boy
tagline:             'with cozy thoughts'
description:         'My name is Andrew McCann, and I write about whatever.'
social-twitter:      AndrewSimulator
social-github:       amccannv
social-email:        andrew@triage.com
social-linkedin:     amccannv
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Andrew McCann
  email:             andrew@triage.com

plugins:
    [jekyll-paginate]
